"""Add index to Skill, Song and Warmup to enable efficient call by REST API

Revision ID: 333bcd4b4c3
Revises: None
Create Date: 2014-12-06 00:29:22.543600

"""

# revision identifiers, used by Alembic.
revision = '333bcd4b4c3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=True)
    op.create_index(op.f('ix_song_title'), 'song', ['title'], unique=True)
    op.create_index(op.f('ix_warmup_name'), 'warmup', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warmup_name'), table_name='warmup')
    op.drop_index(op.f('ix_song_title'), table_name='song')
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    ### end Alembic commands ###
